// <auto-generated />
namespace Demo_Export_OfficeWord.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateDB_Second : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateDB_Second));
        
        string IMigrationMetadata.Id
        {
            get { return "202202091256537_updateDB_Second"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
